// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/psihachina/windfarms-backend/models"
)

// MockAuthorization is a mock of Authorization interface.
type MockAuthorization struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationMockRecorder
}

// MockAuthorizationMockRecorder is the mock recorder for MockAuthorization.
type MockAuthorizationMockRecorder struct {
	mock *MockAuthorization
}

// NewMockAuthorization creates a new mock instance.
func NewMockAuthorization(ctrl *gomock.Controller) *MockAuthorization {
	mock := &MockAuthorization{ctrl: ctrl}
	mock.recorder = &MockAuthorizationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorization) EXPECT() *MockAuthorizationMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockAuthorization) CreateUser(user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthorizationMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthorization)(nil).CreateUser), user)
}

// GetUser mocks base method.
func (m *MockAuthorization) GetUser(username, password string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", username, password)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthorizationMockRecorder) GetUser(username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAuthorization)(nil).GetUser), username, password)
}

// MockWindfarms is a mock of Windfarms interface.
type MockWindfarms struct {
	ctrl     *gomock.Controller
	recorder *MockWindfarmsMockRecorder
}

// MockWindfarmsMockRecorder is the mock recorder for MockWindfarms.
type MockWindfarmsMockRecorder struct {
	mock *MockWindfarms
}

// NewMockWindfarms creates a new mock instance.
func NewMockWindfarms(ctrl *gomock.Controller) *MockWindfarms {
	mock := &MockWindfarms{ctrl: ctrl}
	mock.recorder = &MockWindfarmsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindfarms) EXPECT() *MockWindfarmsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWindfarms) Create(userID string, item models.Windfarm) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, item)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWindfarmsMockRecorder) Create(userID, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWindfarms)(nil).Create), userID, item)
}

// Delete mocks base method.
func (m *MockWindfarms) Delete(userID, windfarmID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userID, windfarmID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWindfarmsMockRecorder) Delete(userID, windfarmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWindfarms)(nil).Delete), userID, windfarmID)
}

// GetAll mocks base method.
func (m *MockWindfarms) GetAll(userID string) ([]models.Windfarm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", userID)
	ret0, _ := ret[0].([]models.Windfarm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWindfarmsMockRecorder) GetAll(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWindfarms)(nil).GetAll), userID)
}

// GetByID mocks base method.
func (m *MockWindfarms) GetByID(userID, windfarmID string) (models.Windfarm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", userID, windfarmID)
	ret0, _ := ret[0].(models.Windfarm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWindfarmsMockRecorder) GetByID(userID, windfarmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWindfarms)(nil).GetByID), userID, windfarmID)
}

// Update mocks base method.
func (m *MockWindfarms) Update(userID, windfarmID string, input models.UpdateWindfarmInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", userID, windfarmID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWindfarmsMockRecorder) Update(userID, windfarmID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWindfarms)(nil).Update), userID, windfarmID, input)
}

// MockTurbines is a mock of Turbines interface.
type MockTurbines struct {
	ctrl     *gomock.Controller
	recorder *MockTurbinesMockRecorder
}

// MockTurbinesMockRecorder is the mock recorder for MockTurbines.
type MockTurbinesMockRecorder struct {
	mock *MockTurbines
}

// NewMockTurbines creates a new mock instance.
func NewMockTurbines(ctrl *gomock.Controller) *MockTurbines {
	mock := &MockTurbines{ctrl: ctrl}
	mock.recorder = &MockTurbinesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTurbines) EXPECT() *MockTurbinesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTurbines) Create(userID string, turbine models.Turbine, outputs models.Outputs) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, turbine, outputs)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTurbinesMockRecorder) Create(userID, turbine, outputs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTurbines)(nil).Create), userID, turbine, outputs)
}

// Delete mocks base method.
func (m *MockTurbines) Delete(userID, turbineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userID, turbineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTurbinesMockRecorder) Delete(userID, turbineID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTurbines)(nil).Delete), userID, turbineID)
}

// GetAll mocks base method.
func (m *MockTurbines) GetAll(userID string) ([]models.Turbine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", userID)
	ret0, _ := ret[0].([]models.Turbine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTurbinesMockRecorder) GetAll(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTurbines)(nil).GetAll), userID)
}

// GetByID mocks base method.
func (m *MockTurbines) GetByID(userID, turbineID string) (models.Turbine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", userID, turbineID)
	ret0, _ := ret[0].(models.Turbine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTurbinesMockRecorder) GetByID(userID, turbineID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTurbines)(nil).GetByID), userID, turbineID)
}

// Update mocks base method.
func (m *MockTurbines) Update(userID, turbineID string, input models.UpdateTurbineInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", userID, turbineID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTurbinesMockRecorder) Update(userID, turbineID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTurbines)(nil).Update), userID, turbineID, input)
}

// MockWinds is a mock of Winds interface.
type MockWinds struct {
	ctrl     *gomock.Controller
	recorder *MockWindsMockRecorder
}

// MockWindsMockRecorder is the mock recorder for MockWinds.
type MockWindsMockRecorder struct {
	mock *MockWinds
}

// NewMockWinds creates a new mock instance.
func NewMockWinds(ctrl *gomock.Controller) *MockWinds {
	mock := &MockWinds{ctrl: ctrl}
	mock.recorder = &MockWindsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWinds) EXPECT() *MockWindsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWinds) Create(userID, windfarmID string, winds []models.Wind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, windfarmID, winds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWindsMockRecorder) Create(userID, windfarmID, winds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWinds)(nil).Create), userID, windfarmID, winds)
}

// GetAll mocks base method.
func (m *MockWinds) GetAll(userID, windfarmID string) ([]models.Wind, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", userID, windfarmID)
	ret0, _ := ret[0].([]models.Wind)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWindsMockRecorder) GetAll(userID, windfarmID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWinds)(nil).GetAll), userID, windfarmID)
}
